// Generated by https://quicktype.io

export interface Pokemon {
  count: number;
  next: string;
  previous: null;
  results: PokemonDetails[];
}

export interface PokemonDetails {
  name: string;
  url: string;
  picture: string;
}

export interface NewListPokemon {
  id: string;
  name: string;
  picture: string;
}
