// Generated by https://quicktype.io

export interface Pokemon {
  next: string;
  results: PokemonDetails[];
  loading: boolean;
  error: any;
}

export interface PokemonDetails {
  name: string;
  url: string;
  picture: string;
}

export interface NewListPokemon {
  id: string;
  name: string;
  picture: string;
  imgColor?: string;
  textColor?: string;
}
export interface PokemonFullDetails {
  abilities: Ability[];
  base_experience: number;
  forms: Species[];
  height: number;
  held_items: any[];
  id: string;
  is_default: boolean;
  location_area_encounters: string;
  moves: Move[];
  name: string;
  order: number;
  past_types: any[];
  species: Species;
  sprites: Sprites;
  stats: Stat[];
  types: Type[];
  weight: number;
}

export interface Ability {
  ability: Species;
  is_hidden: boolean;
  slot: number;
}

export interface Species {
  name: string;
  url: string;
}

export interface Move {
  move: Species;
}
export interface Sprites {
  back_default: string;
  back_female: null;
  back_shiny: string;
  back_shiny_female: null;
  front_default: string;
  front_female: null;
  front_shiny: string;
  front_shiny_female: null;
  animated?: Sprites;
}
export interface Stat {
  base_stat: number;
  effort: number;
  stat: Species;
}

export interface Type {
  slot: number;
  type: Species;
}
